### ISSUE TITLE
Rank algoritmasinin yazilmasi

### ISSUE THREAD

**Issue by hpolatyuruk** [hpolatyuruk/linkwind#29]
https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d

https://news.ycombinator.com/item?id=13867739

https://lobste.rs/about

downvote olup olmadiginida arastiralim.

**Comment by sedataktas** [comment]
http://www.righto.com/2013/11/how-hacker-news-ranking-really-works.html
Bu makalede penalty ve rank sistemini anlatmış. Biz basitçe oradaki formülle başlayabiliriz. Penalty sistemine neyin dahil olduğu ile alakalı da bilgiler var. Bir post'un 40 yoruma ulaşması penaltıyı artırıyor olarak görünüyor veya bazı siteler kara listede ve bu yüzden penalty olarak değerlendiriliyor. Penalty ne kadar 0'a yakınsa bir postun score'u o kadar düşüyor haliyle.
