### ISSUE TITLE
Eksik dosyalar hakkında

### ISSUE THREAD

**Issue by zafer06** [hpolatyuruk/linkwind#49]
Projeyi bilgisayarıma indirdim ama galiba bazı dosyalar eksik yada ben bulamadım. Örneğin docker-compose.yml içinde tanımlı _db.prod.dockerfile_, _nginx.conf_ dosyalarını göremiyorum?

Ayrıca geliştiriciler için bir başlanıç kılavuzu iyi olurdu.

**Comment by hpolatyuruk** [comment]
Projeye ilgi gosterip indirdigin icin tesekkur ederim Zafer.

Bahsettigin dosyalar aslinda onceki versionlardan kalan gereksiz dosyalar. Onlari kaldiracagiz.

Gelistiriciler icin klavuz geri bildirimin icin de tesekkur ederim. Todo listemizde suanda.

Iyi gunler.
"Zafer Çelenk" <notifications@github.com> wrote:
“Projeyi bilgisayarıma indirdim ama galiba bazı dosyalar eksik yada ben bulamadım. Örneğin docker-compose.yml içinde tanımlı db.prod.dockerfile, nginx.conf dosyalarını göremiyorum?

Ayrıca geliştiriciler için bir başlanıç kılavuzu iyi olurdu.”

**Comment by zafer06** [comment]
İlgin için ben teşekkür ederim Hüseyin.
